#!/bin/bash

# Takes a FLAC file and makes an MPEG-4 audio file.

# Usage: flactom4a flac-file

# Better to use with parallel, from the moreutils package:
# parallel flactom4a -- *.flac

if [[ ! -f $1 ]]
then
    echo "Error: '$1' does not exist"
    exit 1
fi

inextension="flac"
outextension="m4a"

flac --decode --stdout "$1" | faac -o "$(basename "${1%.$inextension}.$outextension")" -
