#!/bin/bash

# Takes a FLAC file and makes an MP3 audio file.

# Usage: flactomp3 flac-files

# Better to use with parallel, from the moreutils package:
# parallel flactomp3 -- *.flac

if [[ ! -f $1 ]]
then
    echo "Error: '$1' does not exist"
    exit 1
fi

inextension="flac"
outextension="mp3"

flac --decode --stdout "$1" | lame --preset extreme - "$(basename "${1%.$inextension}.$outextension")"
