#!/bin/bash

# Usage: flactomp3 "directory-containing-flac-files"

if [[ ! -d $1 ]] ; then
    echo "Error: directory '$1' does not exist"
    exit 1
fi

cd "$1"

inextension="flac"
outextension="mp3"

listing="$(find . -name "*.$inextension")"
#echo "listing $1:
#${listing}"
#echo

# IFS holds word delimter characters. see the "Word Splitting" section of the
# bash manual
IFS='\
'
for infile in ${listing}; do
    #echo "filename: $filename"
    flac --decode --stdout "$infile" | lame --preset extreme - "${infile%.$inextension}.$outextension"
done
