#!/usr/bin/perl -w
# Copyright (C) 2006 Kenyon Ralph <kralph@gmail.com>
# chapter 10, exercise 1

use strict;

my $secret = int(1 + rand 100);
#print "$secret\n";

while (1) {
    print "Enter guess of number between 1 and 100: ";
    chomp(my $guess = <STDIN>);
    if ($guess =~ /quit|exit|^\s*$/i) {
	exit;
    }
    if ($guess == $secret) {
	print "Correct!\n";
	exit;
    }
    ($guess < $secret) ? print "Too low.\n" : print "Too high.\n";
}
