#!/usr/bin/perl -w
# Copyright (C) 2006 Kenyon Ralph <kralph@gmail.com>
# chapter 11, exercise 2

use strict;

die "No file names supplied!\n" unless @ARGV;

my $oldest = shift @ARGV;
my $age = -M $oldest;
for (@ARGV) {
    if (-M $_ > -M $oldest) {
	$oldest = $_;
	$age = -M $oldest;
    }
}
print "Oldest file: '$oldest', age: $age days\n";
