#!/usr/bin/perl -w
# Copyright (C) 2007 Kenyon Ralph <kralph@gmail.com>
# chapter 12, exercise 8

use strict;

opendir DIR, "." or die "Cannot open current directory: $!";
for (readdir DIR) {
    if(my $where = readlink $_) {
	print "$_ -> $where\n";
    }
}
