#!/usr/bin/perl -w
# Copyright (C) 2007 Kenyon Ralph <kralph@gmail.com>
# chapter 12, exercise 7

use strict;
use File::Basename;
use File::Spec;

#print scalar @ARGV;
my ($option, $from, $to);

if (scalar @ARGV == 3) {
    ($option, $from, $to) = @ARGV;
} elsif (scalar @ARGV == 2) {
    ($from, $to) = @ARGV;
} else {
    die "need from-file and to-file\n";
}
#print "from $from to $to\n";

$to = File::Spec->catfile($to, basename $from) if -d $to;
die "can't link $from to $to: $to exists\n" if -e $to;

if ($option eq "-s") {
    if (symlink $from, $to) {
	print "symlinked $to to $from\n";
    } else {
	die "symlink $to to $from failed: $!\n";
    }
} elsif (link $from, $to) {
    print "linked $from to $to\n";
} else {
    die "link $from to $to failed: $!\n";
}
