#!/usr/bin/perl -w
# Copyright (C) 2007 Kenyon Ralph <kralph@gmail.com>
# chapter 12, exercise 5

use strict;
use File::Basename;
use File::Spec;

my ($from, $to) = @ARGV;
die "need two arguments, from-file and to-file\n" unless defined($to);
#print "from $from to $to\n";

$to = File::Spec->catfile($to, basename $from) if -d $to;
die "can't rename $from to $to: $to exists\n" if -e $to;
if (rename $from, $to) {
    print "renamed $from to $to\n";
} else {
    die "rename $from to $to failed: $!\n";
}
