#!/usr/bin/perl -w
# Copyright (C) 2007 Kenyon Ralph <kralph@gmail.com>
# chapter 12, exercise 2

use strict;

print "Enter directory to change to: ";
chomp(my $dir = <STDIN>);
#print "entered $dir\n";

if($dir =~ /\s+/ || $dir eq "") {
    #print "\$dir empty\n";
    chdir or die "cannot chdir to your home directory: $!";
} else {
    #print "\$dir has $dir\n";
    chdir $dir or die "cannot chdir to $dir: $!";
}

#print glob "*";
foreach (sort glob "* .*") {
    print $_ . "\n";
}
