#!/usr/bin/perl -w
# Copyright (C) 2007 Kenyon Ralph <kralph@gmail.com>
# chapter 13, exercise 1

use strict;

my @numbers;

push @numbers, split while <>;

for (sort { $a <=> $b } @numbers) {
    printf "%10g\n", $_;
}
