#!/usr/bin/perl -w
# Copyright (C) 2007 Kenyon Ralph <kralph@gmail.com>
# chapter 13, exercise 3

use strict;

my $string = "This is a test.";
my $substring = " ";

{
    my $idx = 0;
    my $last = -1;

    while ($idx != -1) {
	$idx = index($string, $substring, $last+1);
	print "$idx\n" if $idx != -1;
	$last = $idx;
    }
}
