#!/usr/bin/perl -w
# Copyright (C) 2007 Kenyon Ralph <kralph@gmail.com>
# chapter 14, exercise 3

use strict;

if (`date` =~ /^(Sat|Sun)/) {
    print "go play\n";
} else {
    print "get to work\n";
}
