#!/usr/bin/perl -w
# Copyright (C) 2007 Kenyon Ralph <kralph@gmail.com>
# chapter 14, exercise 2

use strict;

open STDOUT, ">ls.out" or die "can't write to ls.out: $!";
open STDERR, ">ls.err" or die "can't write to ls.err: $!";
chdir "/" or die "couldn't change dir: $!";
exec "ls", "-l" or die "couldn't do ls: $!";
