#!/usr/bin/perl -w
# Copyright (C) 2007 Kenyon Ralph <kralph@gmail.com>
# chapter 14, exercise 1

use strict;

chdir "/" or die "couldn't change dir: $!";
exec "ls", "-l" or die "couldn't do ls: $!";
