#!/usr/bin/perl -w
# Copyright (C) 2007 Kenyon Ralph <kralph@gmail.com>
# chapter 15, exercise 3

use strict;
use File::Spec;
use File::Basename;

my @paths = `./ex15-2-absolute-paths`;
#print map "$_", @paths;

# File::Spec way:
print map { (File::Spec->splitpath($_))[2] } @paths;

print "\n";

# File::Basename way:
print map { (fileparse($_))[0] } @paths;
