#!/usr/bin/perl -w
# Copyright (C) 2006 Kenyon Ralph <kralph@gmail.com>
# chapter 2 exercise 5

print "Enter a string: ";
chomp($str = <STDIN>);
print "Enter a number: ";
chomp($num = <STDIN>);
print(($str . "\n") x $num);
