#!/usr/bin/perl -w
# Copyright (C) 2006 Kenyon Ralph <kralph@gmail.com>
# chapter 2 exercise 4

print "Number one: ";
chomp($num1 = <STDIN>);
print "Number two: ";
chomp($num2 = <STDIN>);
print "Product: " . $num1 * $num2 . "\n";
