#!/usr/bin/perl -w
# Copyright (C) 2006 Kenyon Ralph <kralph@gmail.com>
# chapter 3 exercise 2

@names = qw(fred betty barney dino wilma pebbles bamm-bamm);

chomp(@lines = <STDIN>);
print "\n";
foreach(@lines) {
    print $names[$_ - 1];
    print ' ';
}
print "\n";
