#!/usr/bin/perl -w
# Copyright (C) 2006 Kenyon Ralph <kralph@gmail.com>
# chapter 4 exercise 3

use strict;

sub total {
    my $sum;
    foreach (@_) {
	$sum += $_;
    }
    return $sum;
}

sub average {
    return &total(@_) / @_;
}

sub above_average {
    my @results;
    my $avg = &average(@_);
    foreach (@_) {
	if ($_ > $avg) {
	    push @results, $_;
	}
    }
    return @results;
}

my @fred = &above_average(1..10);
print "\@fred is @fred\n";
print "(Should be 6 7 8 9 10)\n";
my @barney = &above_average(100, 1..10);
print "\@barney is @barney\n";
print "(should be just 100)\n";
