#!/usr/bin/perl -w
# Copyright (C) 2006 Kenyon Ralph <kralph@gmail.com>
# chapter 5, exercise 3

use strict;

print "Enter column width then strings on separate lines:\n";
chomp(my @input = <STDIN>);
my $width = shift @input;
print "1234567890" x (($width+9)/10), "\n";
foreach (@input) {
    printf "%${width}s\n", $_;
}
