#!/usr/bin/perl -w
# Copyright (C) 2006 Kenyon Ralph <kralph@gmail.com>
# chapter 8, exercise 3

use strict;

while(<>) {
    chomp;
    if (/(\b\w*a\b)/) {
	print "Matched: |$`<$&>$'|, \$1 contains '$1'\n";
    } else {
	print "No match: |$_|\n";
    }
}
