#!/usr/bin/perl -w
# Copyright (C) 2006 Kenyon Ralph <kralph@gmail.com>
# chapter 8, exercise 4

use strict;

while(<>) {
    chomp;
    if (/\b(\w*a)\b(.{0,5})/) {
	print "Matched: |$`<$&>$'|, \$1='$1', \$2='$2'\n";
    } else {
	print "No match: |$_|\n";
    }
}
