#!/usr/bin/perl -w
# Copyright (C) 2006 Kenyon Ralph <kralph@gmail.com>
# chapter 9, exercise 1

use strict;

my $what = 'fred|barney';

while(<>) {
    chomp;
    if(/($what){3}/) {
	print "Matched: |$`<$&>$'|\n";
    } else {
	print "No match: |$_|\n";
    }
}
