#!/usr/bin/perl -w
# Copyright (C) 2006 Kenyon Ralph <kralph@gmail.com>
# chapter 9, exercise 4

use strict;

$^I = ".bak";

while (<>) {
    if ( m{^#!} ) {
	print "$_# Copyright (C) 2006 Kenyon Ralph <kralph\@gmail.com>\n";
    } else { print }
}
