#!/bin/bash

# Usage: flactomp3 "directory-containing-flac-files"

if [[ ! -d $1 ]] ; then
    echo "Error: directory '$1' does not exist"
    exit 1
fi

cd "$1"

listing=`ls`
#echo "listing $1:
#${listing}"
#echo

# IFS holds word delimter characters. see the "Word Splitting" section of the
# bash manual
IFS='\
'
inextension="flac"
outextension="mp3"
for infile in ${listing}; do
    filename=`echo "$infile" | sed {s/\.$inextension//}`
    #echo "filename: $filename"
    flac -dc "$infile" | lame --preset extreme - "$filename.$outextension"
done
